export const SET_TOKEN = "SET_TOKEN";
export const SET_REGISTERED_EMAIL = "SET_REGISTERED_EMAIL";
export const SET_VERIFY_EMAIL = "SET_VERIFY_EMAIL";
export const SET_IMAGE_BASE_URL = "SET_IMAGE_BASE_URL";
export const SET_CART_ITEM_COUNT = "SET_CART_ITEM_COUNT";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SET_ALL_COLOR_SIZE = "SET_ALL_COLOR_SIZE";

// export const SET_PROFILE_DATA = "SET_PROFILE_DATA";
// export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE";

// export const SET_APP_SETTING_PUBLIC_DATA = "SET_APP_SETTING_PUBLIC_DATA";
// export const SET_NOTIFICATION_COUNT = "SET_NOTIFICATION_COUNT";
